### ISSUE TITLE
Minify process break query parameters in links

### ISSUE THREAD

**Issue by Skylsmoi** [algoo/jfmengine#61]
The minify process includes two bugs:

1. strings like `?offer=start&current_tab=Individual` are minified as `?offer=start¤t_tab=Individual`
2. in markdown content, line return is replaced with nothing gluing last word of a line with first word of next line

Second point is due to using  beautiful soup with the following extra code: `file.write(str(soup).replace('\n', ''))`

**Comment by lebouquetin** [comment]
The way I fixed this is to use the "agressive" `minify-html` module; see https://pypi.org/project/minify-html/

I also added some output when minifying / beautifying:

Minifying output example:

```
[-30.8%] /tmp/dist-prod/index.html
[-31.3%] /tmp/dist-prod/en/index.html
[-23.9%] /tmp/dist-prod/en/customer-testimonials.html
```

Beautifying output example:

```
[+44.6%] /tmp/dist-prod/index.html
[+45.5%] /tmp/dist-prod/en/index.html
[+31.5%] /tmp/dist-prod/en/customer-testimonials.html
```
